CREATE TABLE IF NOT EXISTS hotel_user (
    id BIGINT PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    membership_level VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
