server:
  port: 8720

spring:
  application:
    name: sentinel-token-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}

sentinel:
  token-server:
    namespaces: ${SENTINEL_CLUSTER_NAMESPACES:sentinel-bff-service,sentinel-a-service,sentinel-b-service}
    port: ${SENTINEL_CLUSTER_SERVER_PORT:18730}
    idle-seconds: ${SENTINEL_CLUSTER_SERVER_IDLE_SECONDS:600}
    max-allowed-qps: ${SENTINEL_CLUSTER_SERVER_MAX_ALLOWED_QPS:10000}
    nacos:
      server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      namespace: ${NACOS_NAMESPACE:pro}
      group-id: ${SENTINEL_CLUSTER_RULE_GROUP:SENTINEL_GROUP}
      flow-rule-data-ids: ${SENTINEL_CLUSTER_FLOW_RULE_DATA_IDS:sentinel-bff-service-flow-rules.json,sentinel-a-service-flow-rules.json,sentinel-b-service-flow-rules.json}
