server:
  port: 8089

spring:
  application:
    name: mq-demo-bff-service
  config:
    import: optional:nacos:${spring.application.name}.yaml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:pro}
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:pro}
        file-extension: yaml
    sentinel:
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8858}

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
